shared:
    settings:
        email:
            addresses: [moloch.build@oath.com]
            statuses: [SUCCESS, FAILURE]
jobs:
    main:
        image: andywick/moloch-build-7:1
        steps:
            - slack-success: |
                BUILD_VERSION=`git describe --tags`
                BODY="{\"username\": \"MolochBuild\", \"text\":\"It worked! $GIT_BRANCH  $BUILD_VERSION $SD_PULL_REQUEST\"}"
                echo $BODY
                curl -X POST \
                  -H "Content-type: application/json" \
                  --data "$BODY" \
                  https://www.google.com

